create type public.user_type as enum ('CUSTOMER', 'SHOP');

create table if not exists public.users (
  id bigint generated by default as identity constraint users_pkey primary key,
  name varchar,
  email varchar,
  phone varchar,
  type public.user_type,
  password text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone
);